services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${PROJECT_PATH}/certs:/etc/nginx/certs:ro
      - ${PROJECT_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${PROJECT_PATH}/html:/usr/share/nginx/html
    networks:
      - nginx-proxy
    restart: unless-stopped

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PROJECT_PATH}/certs:/etc/nginx/certs
      - ${PROJECT_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${PROJECT_PATH}/html:/usr/share/nginx/html
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
